name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  checkstyle:
    name: Checkstyle Report
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/reports/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Tests compose
        run: mvn test

  build:
    name: Build (Skip Tests)
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application (Skip Tests)
        run: mvn package -DskipTests

  docker-build-mr:
    name: Build & Push Docker Image for Merge Request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mr:${{ github.sha }}

  docker-build-main:
    name: Build & Push Docker Image for Main Branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/main:latest
